from __future__ import annotations

import hashlib
from collections.abc import Mapping
from datetime import datetime, timedelta, timezone
from typing import Any

from .reply_template_store import ReplyTemplates, render_template
from .rule_contracts import RuleDecision
from .transaction_state_store import StateRevisionConflict, TransactionStateStore


def _text(value: object) -> str | None:
    normalized = str(value or "").strip()
    return normalized or None


def _pick(source: object, *fields: str) -> str | None:
    if not isinstance(source, Mapping):
        return None
    for field in fields:
        value = _text(source.get(field))
        if value:
            return value
    return None


def _explicit_human_takeover(body: Mapping[str, Any]) -> bool:
    """Return whether the current platform message is a real seller message.

    A seller's ordinary reply is already an unambiguous handoff signal. The
    previous implementation required special words, which allowed a human
    reply such as a manually typed quantity prompt to race deterministic rules.
    Messages marked as generated by the plugin and non-chat transaction cards
    are excluded.
    """
    envelope = body.get("envelope") if isinstance(body.get("envelope"), Mapping) else {}
    payload = envelope.get("payload") if isinstance(envelope.get("payload"), Mapping) else {}
    current_id = _pick(payload, "remoteMessageId", "remote_message_id", "messageId", "message_id")
    if not current_id:
        return False
    messages = body.get("recent_messages") if isinstance(body.get("recent_messages"), list) else []
    for message in messages:
        if not isinstance(message, Mapping) or message.get("agent_generated") is True:
            continue
        if _pick(message, "messageId", "message_id", "remoteMessageId", "remote_message_id", "id") != current_id:
            continue
        direction = (_pick(message, "direction", "sender", "role") or "").lower()
        if direction not in {"seller", "shop", "staff", "human", "manual", "outbound", "sent"}:
            return False
        message_type = str(message.get("messageType", message.get("message_type", ""))).strip()
        if message_type and message_type not in {"1", "2"}:
            return False
        content = message.get("content")
        text = _pick(content, "text", "content") if isinstance(content, Mapping) else _text(content)
        return bool(text)
    return False


def _official_order_amount_cents(order: Mapping[str, Any]) -> int | None:
    for field in ("payment", "amount_cents", "priceFee", "price_fee"):
        value = order.get(field)
        if isinstance(value, int) and not isinstance(value, bool) and value > 0:
            return value
    return None


def _future_iso_timestamp(value: object) -> bool:
    raw = str(value or "").strip()
    if not raw:
        return False
    try:
        parsed = datetime.fromisoformat(raw)
    except ValueError:
        return False
    if parsed.tzinfo is None:
        parsed = parsed.replace(tzinfo=timezone.utc)
    return parsed > datetime.now(timezone.utc)


def _fixed_transaction_reply(
    *, state: str, transition_code: str, event_id: str,
    current: object, templates: ReplyTemplates,
) -> dict[str, Any] | None:
    template_name: str | None = None
    variables: dict[str, object] = {}
    if state == "QUOTED" and transition_code == "explicit_quote_confirmation_required":
        template_name = "quote_confirmation_clarify_template"
    elif (
        state == "CONFIRMED"
        and transition_code == "quote_confirmation_recorded"
        and isinstance(getattr(current, "confirmed_ticket_count", None), int)
    ):
        template_name = "order_submit_unpaid_template"
        variables = {"张数": current.confirmed_ticket_count}
    elif state == "PAID_WAITING_FULFILLMENT" and transition_code == "official_payment_verified":
        template_name = "payment_success_pending_ticket_template"
    elif state == "MANUAL_HOLD" and transition_code in {
        "payment_before_amount_verification", "paid_amount_mismatch", "paid_amount_unverified",
    }:
        template_name = "payment_manual_review_template"
    elif state == "TICKET_SENT":
        template_name = "order_shipped_template"
    elif state in {"ORDER_UNVERIFIED", "MANUAL_HOLD"} and transition_code not in {
        "explicit_human_takeover", "multiple_active_orders_detected", "fixed_switch_rejected", "fixed_switch_expired",
    }:
        template_name = "manual_review_template"
    if template_name is None:
        return None
    text = render_template(getattr(templates, template_name), variables)
    if not text:
        return None
    return {
        "id": f"{event_id}:fixed:{template_name}", "type": "send_message",
        "text": text, "rule_governed": True,
        "dedupe_key": f"{getattr(current, 'state_id', 'unbound')}:{template_name}",
    }


class RuleStateCoordinator:
    """Reduce one candidate outcome into authoritative state before commands exist."""

    def __init__(
        self, store: TransactionStateStore, quote_store: object | None = None,
        reply_template_store: object | None = None, liangpiao_order_phone: str = "",
    ) -> None:
        self._store = store
        self._quote_store = quote_store
        self._reply_template_store = reply_template_store
        self._liangpiao_order_phone = str(liangpiao_order_phone or "").strip()

    def _templates(self) -> ReplyTemplates:
        current = getattr(self._reply_template_store, "current", None)
        return current() if callable(current) else ReplyTemplates()

    @staticmethod
    def _identity(body: Mapping[str, Any]) -> dict[str, str] | None:
        envelope = body.get("envelope") if isinstance(body.get("envelope"), Mapping) else {}
        payload = envelope.get("payload") if isinstance(envelope.get("payload"), Mapping) else {}
        session = body.get("session") if isinstance(body.get("session"), Mapping) else {}
        order = body.get("order") if isinstance(body.get("order"), Mapping) else {}
        values = {
            "tenant_id": _pick(envelope, "tenantId", "tenant_id"),
            "shop_id": _pick(session, "accountUnb", "account_unb") or _pick(order, "accountUnb", "account_unb") or _pick(payload, "accountUnb", "account_unb"),
            "buyer_id": _pick(session, "peerUnb", "peer_unb") or _pick(order, "buyerUnb", "buyer_unb", "peerUnb", "peer_unb") or _pick(payload, "peerUnb", "peer_unb"),
            "chat_id": _pick(session, "chatId", "chat_id") or _pick(order, "chatId", "chat_id") or _pick(payload, "chatId", "chat_id"),
        }
        return {key: value for key, value in values.items() if value} if all(values.values()) else None

    @staticmethod
    def _event_id(body: Mapping[str, Any]) -> str | None:
        envelope = body.get("envelope")
        return _pick(envelope, "id", "eventId", "event_id")

    def record_event_decision(
        self, body: Mapping[str, Any], result: dict[str, object],
    ) -> dict[str, object]:
        identity = self._identity(body)
        event_id = self._event_id(body)
        decision = result.get("decision")
        if identity is None or event_id is None or not isinstance(decision, Mapping):
            return result
        current = self._store.get_or_create(**identity)
        actions = decision.get("actions") if isinstance(decision.get("actions"), list) else []
        reason = _text(decision.get("reason")) or "no_transition"
        target_state = current.flow_state if current.flow_state != "NEW" else "COLLECTING"
        transition_code = "event_processed"
        updates: dict[str, object] = {}
        handoff_reason: str | None = None

        envelope = body.get("envelope") if isinstance(body.get("envelope"), Mapping) else {}
        event_type = _pick(envelope, "event")
        order = body.get("order") if isinstance(body.get("order"), Mapping) else {}
        order_id = _pick(order, "orderId", "order_id") or _pick(envelope.get("payload"), "orderId", "order_id")
        order_status = (_pick(order, "orderStatus", "order_status", "status") or "").lower()
        observed_order_amount = _official_order_amount_cents(order)
        paid_lifecycle_signal = bool(
            (order_status in {"2", "paid", "payment_success", "已付款", "支付成功"} or _pick(order, "payTime", "pay_time"))
            and (event_type == "order.paid" or reason in {
                "authoritative_paid_status_reply_ready", "authoritative_payment_confirmation_ready",
            })
        )
        payment_gate_verified = bool(
            current.flow_state in {"WAITING_PAYMENT", "PAID_WAITING_FULFILLMENT"}
            and current.price_change_status == "succeeded"
            and current.payment_status in {"unpaid", "verified_paid"}
            and current.order_id == order_id
            and isinstance(current.target_amount_cents, int)
            and observed_order_amount == current.target_amount_cents
        )
        quote_record = None
        active_quote_record = None
        if self._quote_store is not None and callable(getattr(self._quote_store, "get_record", None)):
            get_record = self._quote_store.get_record
            quote_record = get_record(tenant_id=identity["tenant_id"], record_id=event_id)
            if current.active_quote_record_id and current.active_quote_record_id != event_id:
                active_quote_record = get_record(
                    tenant_id=identity["tenant_id"], record_id=current.active_quote_record_id,
                )
        same_quote_terms = bool(
            isinstance(quote_record, Mapping)
            and isinstance(active_quote_record, Mapping)
            and quote_record.get("terms_fingerprint")
            and quote_record.get("terms_fingerprint") == active_quote_record.get("terms_fingerprint")
        )
        changed_failed_quote = bool(
            isinstance(quote_record, Mapping)
            and quote_record.get("status") not in {None, "succeeded"}
            and isinstance(active_quote_record, Mapping)
            and quote_record.get("terms_fingerprint")
            and active_quote_record.get("terms_fingerprint")
            and not same_quote_terms
            and not current.order_id
        )
        if changed_failed_quote:
            invalidate = getattr(self._quote_store, "invalidate", None)
            if callable(invalidate):
                invalidated = invalidate(
                    tenant_id=identity["tenant_id"],
                    record_id=str(active_quote_record.get("record_id") or current.active_quote_record_id),
                    reason="superseded_by_new_failed_quote_attempt",
                )
                if isinstance(invalidated, Mapping):
                    active_quote_record = invalidated
        if event_type in {"order.refund.finished", "order.refunded"} and order_id and current.active_quote_record_id:
            release_binding = getattr(self._quote_store, "release_order_binding", None)
            if callable(release_binding):
                released = release_binding(
                    record_id=current.active_quote_record_id,
                    tenant_id=identity["tenant_id"],
                    shop_id=identity["shop_id"],
                    buyer_id=identity["buyer_id"],
                    chat_id=identity["chat_id"],
                    order_id=order_id,
                    released_at=datetime.now(timezone.utc),
                )
                if isinstance(released, Mapping):
                    active_quote_record = released
        terminal_states = {"COMPLETED", "CANCELLED", "REFUNDED"}
        change_action = next(
            (action for action in actions if isinstance(action, Mapping) and action.get("type") == "change_order_price"),
            None,
        )
        starts_replacement_quote_generation = bool(
            isinstance(quote_record, Mapping)
            and quote_record.get("status") in {None, "succeeded"}
            and current.active_quote_record_id != event_id
            and (
                (
                    current.flow_state in {"QUOTED", "CONFIRMED", "QUOTE_EXPIRED"}
                    and not current.order_id
                    and not same_quote_terms
                )
                or current.flow_state in terminal_states
            )
        )
        starts_replacement_order_generation = bool(
            current.flow_state in terminal_states
            and order_id
            and current.order_id != order_id
            and (
                event_type in {"order.created", "order.paid", "order.shipped"}
                or order_status in {
                    "1", "2", "3", "pending", "pending_payment", "paid", "shipped",
                    "待付款", "已付款", "待发货", "已发货",
                }
            )
        )
        starts_replacement_generation = bool(
            starts_replacement_quote_generation or starts_replacement_order_generation
        )
        start_generation = getattr(self._store, "start_new_generation", None)
        if starts_replacement_generation and callable(start_generation):
            current = start_generation(
                **identity, expected_revision=current.revision,
                event_id=f"{event_id}:generation",
                reason=(
                    "new_order_after_terminal"
                    if starts_replacement_order_generation else "trade_terms_replaced"
                ),
            )

        fixed_switch_recovery_event = bool(
            reason.startswith("fixed_switch_")
            and getattr(current, "fixed_switch_status", "none") in {"pending", "confirmed"}
        )
        terminal_locked = bool(
            current.flow_state in terminal_states
            and not starts_replacement_generation
            and not fixed_switch_recovery_event
        )
        terminal_transaction_reasons = {
            "order_submission_guidance_ready", "confirmed_quote_record_bound_to_order",
            "bound_order_amount_already_matches_quote", "authoritative_order_amount_already_matches_quote",
            "authoritative_payment_confirmation_ready", "authoritative_paid_status_reply_ready",
            "authoritative_shipped_status_reply_ready", "quote_confirmation_clarification_ready",
        }
        terminal_transaction_attempt = bool(
            reason in terminal_transaction_reasons
            or any(
                isinstance(action, Mapping)
                and action.get("type") in {"change_order_price", "send_price_change_confirmation"}
                for action in actions
            )
        )
        explicit_human_takeover = _explicit_human_takeover(body)
        automation_hold_active = bool(
            current.flow_state == "MANUAL_HOLD"
            or getattr(current, "automation_control", "active") != "active"
        )
        multiple_active_orders = bool(
            event_type == "order.created" and current.order_id and order_id
            and current.order_id != order_id
            and current.flow_state not in terminal_states
        )
        if terminal_locked and terminal_transaction_attempt:
            actions = []
            change_action = None
            decision = {**decision, "actions": [], "reason": "terminal_event_ignored"}
        elif event_type in {"order.refund.applied", "order.refund.finished", "order.refunded"}:
            # Official refund facts must be applied even when the transaction
            # was previously held for a payment/price mismatch. Otherwise a
            # refunded order leaves MANUAL_HOLD latched and blocks the buyer's
            # still-open replacement order forever.
            actions = []
            change_action = None
            decision = {**decision, "actions": [], "reason": "official_refund_state_update"}
        elif explicit_human_takeover:
            actions = []
            change_action = None
            decision = {**decision, "actions": [], "reason": "explicit_human_takeover"}
        elif automation_hold_active and not reason.startswith("fixed_switch_"):
            actions = []
            change_action = None
            decision = {**decision, "actions": [], "reason": "automation_hold_active"}
        elif multiple_active_orders:
            actions = []
            decision = {**decision, "actions": [], "reason": "multiple_active_orders_manual_hold"}
        if terminal_locked:
            target_state = current.flow_state
            transition_code = "terminal_event_ignored"
            updates = {}
        elif event_type == "order.refund.applied":
            target_state = "REFUND_PENDING"
            transition_code = "official_refund_pending"
            updates = {
                "order_status": "refund_pending", "payment_status": "refund_pending",
                "order_id": order_id,
                "fixed_switch_source_order_status": "refund_pending",
                "fixed_switch_source_platform_order_id": (
                    current.fixed_switch_source_platform_order_id or current.order_id or order_id
                ),
            }
        elif event_type in {"order.refund.finished", "order.refunded"}:
            target_state = "REFUNDED"
            transition_code = "official_refund_completed"
            updates = {
                "quote_status": "expired", "confirmation_status": "invalidated",
                "active_quote_record_id": None, "confirmed_quote_record_id": None,
                "confirmation_version": None, "confirmation_source": None,
                "confirmation_event_id": None, "confirmed_ticket_count": None,
                "target_amount_cents": None,
                "order_status": "refunded", "payment_status": "refunded",
                "fulfillment_status": "none", "order_id": order_id,
                "price_change_status": "skipped",
                "fixed_switch_source_order_status": "closed",
                "fixed_switch_source_platform_order_id": (
                    current.fixed_switch_source_platform_order_id or current.order_id or order_id
                ),
            }
        elif explicit_human_takeover:
            target_state = "MANUAL_HOLD"
            transition_code = "explicit_human_takeover"
            handoff_reason = "explicit_human_takeover"
            updates = {"automation_control": "human_hold"}
        elif automation_hold_active and not reason.startswith("fixed_switch_"):
            target_state = "MANUAL_HOLD"
            transition_code = "automation_hold_active"
            updates = {}
        elif multiple_active_orders:
            target_state = "MANUAL_HOLD"
            transition_code = "multiple_active_orders_detected"
            handoff_reason = "multiple_active_orders"
        elif reason == "wplus_marker_confirmed_order_guidance":
            target_state = "QUOTED"
            transition_code = "wplus_marker_confirmed_order_guidance"
            updates = {
                "quote_status": "ready",
                "confirmation_status": "pending",
                "expected_inputs": ["ticket_count", "order"],
            }
        elif reason == "fixed_switch_quote_ready":
            fixed_quote_action = next((action for action in actions if isinstance(action, Mapping) and isinstance(action.get("fixed_switch_quote"), Mapping)), None)
            fixed_quote = fixed_quote_action.get("fixed_switch_quote") if isinstance(fixed_quote_action, Mapping) else {}
            target_state = "QUOTED"
            transition_code = "fixed_switch_quote_created"
            updates = {
                "fixed_switch_status": "confirmed",
                "fixed_switch_quote_confirmation_status": "pending",
                "fixed_switch_quote_id": _pick(fixed_quote, "quote_id"),
                "fixed_switch_quote_hash": _pick(fixed_quote, "quote_hash"),
                "fixed_switch_quote_generation": fixed_quote.get("generation"),
                "fixed_switch_confirmation_event_id": event_id,
                "fixed_switch_expires_at": (
                    datetime.now(timezone.utc) + timedelta(minutes=30)
                ).isoformat(),
                "quote_status": "ready", "confirmation_status": "pending",
                "target_amount_cents": fixed_quote.get("amount_fen"),
                "confirmed_ticket_count": fixed_quote.get("ticket_count"),
            }
        elif reason == "fixed_switch_rejected":
            target_state = "MANUAL_HOLD"
            transition_code = "fixed_switch_rejected"
            updates = {"fixed_switch_status": "rejected", "fixed_switch_quote_confirmation_status": "none"}
        elif reason == "fixed_switch_expired":
            target_state = "MANUAL_HOLD"
            transition_code = "fixed_switch_expired"
            updates = {"fixed_switch_status": "expired", "fixed_switch_quote_confirmation_status": "none"}
        elif reason == "fixed_switch_price_confirmed":
            target_state = "CONFIRMED"
            transition_code = "fixed_switch_price_confirmation_recorded"
            updates = {
                "fixed_switch_quote_confirmation_status": "confirmed",
                "quote_status": "ready", "confirmation_status": "confirmed",
                "fixed_switch_replacement_order_id": None,
                "order_id": None, "order_status": "none",
                "price_change_status": "none", "payment_status": "unpaid",
                "fulfillment_status": "none",
            }
        elif reason in {"fixed_switch_quote_failed", "fixed_switch_quote_invalid", "fixed_switch_source_quote_missing", "fixed_switch_source_seats_missing", "fixed_switch_unavailable", "fixed_switch_quote_missing"}:
            target_state = "MANUAL_HOLD"
            transition_code = reason
            handoff_reason = reason
            updates = {"fixed_switch_status": "failed"}
            actions = []
            decision = {**decision, "actions": [], "reason": reason}
        elif (
            order_status in {"4", "completed", "finished", "已完成", "交易成功"}
            and (event_type in {"order.paid", "order.shipped", "order.finished"} or reason == "authoritative_shipped_status_reply_ready")
        ):
            target_state = "COMPLETED"
            transition_code = "official_order_completed"
            updates = {
                "order_status": "completed", "payment_status": "verified_paid",
                "fulfillment_status": "completed", "order_id": order_id,
            }
        elif (
            order_status in {"3", "shipped", "delivered", "已发货", "待收货"}
            and (event_type in {"order.paid", "order.shipped", "order.finished"} or reason == "authoritative_shipped_status_reply_ready")
        ):
            target_state = "TICKET_SENT"
            transition_code = "official_shipment_verified"
            updates = {
                "order_status": "shipped", "payment_status": "verified_paid",
                "fulfillment_status": "shipped", "order_id": order_id,
            }
        elif (
            paid_lifecycle_signal
            and current.fixed_switch_replacement_order_id
            and current.fixed_switch_replacement_order_id != order_id
        ):
            target_state = current.flow_state
            transition_code = "fixed_switch_unbound_paid_ignored"
            updates = {}
            actions = []
            decision = {**decision, "actions": [], "reason": transition_code}
        elif (
            paid_lifecycle_signal
            and current.fixed_switch_replacement_order_id == order_id
            and current.fixed_switch_quote_confirmation_status == "confirmed"
            and not _future_iso_timestamp(current.fixed_switch_expires_at)
        ):
            target_state = "MANUAL_HOLD"
            transition_code = "fixed_switch_quote_expired_after_payment"
            handoff_reason = transition_code
            updates = {
                "fixed_switch_status": "expired",
                "order_status": "paid", "payment_status": "verified_paid",
                "fulfillment_status": "none", "order_id": order_id,
            }
            actions = []
            decision = {**decision, "actions": [], "reason": transition_code}
        elif paid_lifecycle_signal and not payment_gate_verified:
            target_state = "MANUAL_HOLD"
            if observed_order_amount is None:
                transition_code = "paid_amount_unverified"
            elif current.target_amount_cents is not None and observed_order_amount != current.target_amount_cents:
                transition_code = "paid_amount_mismatch"
            else:
                transition_code = "payment_before_amount_verification"
            handoff_reason = transition_code
            updates = {
                "order_status": "paid",
                "payment_status": "mismatch" if transition_code == "paid_amount_mismatch" else "verification_required",
                "fulfillment_status": "none", "order_id": order_id,
            }
            actions = []
            decision = {**decision, "actions": [], "reason": transition_code}
        elif paid_lifecycle_signal:
            target_state = "PAID_WAITING_FULFILLMENT"
            transition_code = "official_payment_verified"
            updates = {
                "order_status": "paid", "payment_status": "verified_paid",
                "fulfillment_status": "pending", "order_id": order_id,
            }
            fixed_switch_paid = bool(
                current.fixed_switch_status == "confirmed"
                and current.fixed_switch_source_order_status == "closed"
                and current.fixed_switch_quote_confirmation_status == "confirmed"
                and current.fixed_switch_replacement_order_id == order_id
                and current.fixed_switch_quote_id
                and current.fixed_switch_quote_hash
                and len(current.fixed_switch_quote_hash) == 64
                and isinstance(current.fixed_switch_quote_generation, int)
                and isinstance(current.confirmed_ticket_count, int)
                and current.fulfillment_status == "none"
                and _future_iso_timestamp(current.fixed_switch_expires_at)
            )
            provider_quote = active_quote_record or quote_record
            if fixed_switch_paid:
                order_action = {
                    "id": f"{event_id}:create-liangpiao-order",
                    "type": "create_liangpiao_order",
                    "order_id": order_id,
                    "quote_id": current.fixed_switch_quote_id,
                    "quote_hash": current.fixed_switch_quote_hash,
                    "confirmation_id": current.fixed_switch_confirmation_event_id or event_id,
                    "latest_buyer_message": "新订单付款已确认，按一口价报价进入出票流程",
                    "buyer_phone": _pick(order, "phone", "mobile", "tel") or self._liangpiao_order_phone,
                    "generation": current.fixed_switch_quote_generation,
                    "ticket_count": current.confirmed_ticket_count,
                    "buyer_confirmed": True,
                    "allow_seat_change": False,
                    "shop_id": identity["shop_id"], "buyer_id": identity["buyer_id"], "chat_id": identity["chat_id"],
                    "trace_id": event_id,
                    "rule_governed": True,
                }
                actions = [order_action, *actions]
                decision = {**decision, "actions": actions}
            elif (
                isinstance(provider_quote, Mapping)
                and provider_quote.get("quote_route") == "liangpiao_exact"
                and _pick(provider_quote, "provider_quote_id", "quote_id")
                and _pick(provider_quote, "provider_quote_hash", "quote_hash")
                and current.confirmation_status == "confirmed"
            ):
                order_action = {
                    "id": f"{event_id}:create-liangpiao-order",
                    "type": "create_liangpiao_order",
                    "order_id": order_id,
                    "quote_id": _pick(provider_quote, "provider_quote_id", "quote_id"),
                    "quote_hash": _pick(provider_quote, "provider_quote_hash", "quote_hash"),
                    "confirmation_id": current.confirmation_event_id or current.confirmation_version or event_id,
                    "latest_buyer_message": "确认下单",
                    "buyer_phone": _pick(order, "phone", "mobile", "tel") or self._liangpiao_order_phone,
                    "generation": int(provider_quote.get("quote_generation") or current.generation),
                    "ticket_count": current.confirmed_ticket_count,
                    "buyer_confirmed": True,
                    "allow_seat_change": False,
                    "shop_id": identity["shop_id"], "buyer_id": identity["buyer_id"], "chat_id": identity["chat_id"],
                    "trace_id": event_id,
                    "rule_governed": True,
                }
                actions = [order_action, *actions]
                decision = {**decision, "actions": actions}
        elif isinstance(change_action, Mapping):
            snapshot = change_action.get("quote_snapshot") if isinstance(change_action.get("quote_snapshot"), Mapping) else {}
            target_state = "PRICE_CHANGING"
            transition_code = "price_change_command_created"
            updates = {
                "quote_status": "ready",
                "confirmation_status": "confirmed",
                "order_status": "bound",
                "price_change_status": "pending",
                "active_quote_record_id": _pick(snapshot, "quote_record_id"),
                "confirmed_quote_record_id": _pick(snapshot, "quote_record_id"),
                "confirmation_version": _pick(snapshot, "confirmation_version"),
                "confirmation_source": _pick(snapshot, "confirmation_source") or "buyer_message",
                "confirmation_event_id": event_id,
                "confirmed_ticket_count": snapshot.get("confirmed_ticket_count"),
                "order_id": _pick(snapshot, "order_id"),
                "target_amount_cents": snapshot.get("target_amount_cents"),
                "price_change_command_id": _pick(change_action, "id"),
                "expected_inputs": [],
            }
            if snapshot.get("fixed_switch") is True:
                updates.update({
                    "fixed_switch_replacement_order_id": _pick(snapshot, "order_id"),
                    "fixed_switch_status": "confirmed",
                    "fixed_switch_quote_confirmation_status": "confirmed",
                })
        elif reason == "order_created_before_quote_requires_explicit_confirmation":
            target_state = "QUOTED"
            transition_code = "order_before_quote_confirmation_required"
            order = body.get("order") if isinstance(body.get("order"), Mapping) else {}
            updates = {
                "quote_status": "ready", "confirmation_status": "pending",
                "order_status": "unverified", "order_id": _pick(order, "orderId", "order_id"),
            }
        elif (
            current.flow_state in {"NEW", "COLLECTING", "FACTS_READY", "QUOTED", "QUOTE_EXPIRED", "MANUAL_HOLD"}
            and isinstance(quote_record, Mapping)
        ):
            if quote_record.get("status") in {None, "succeeded"}:
                target_state = "QUOTED"
                transition_code = "authoritative_quote_created"
                updates = {
                    "quote_status": "ready", "confirmation_status": "pending",
                    "active_quote_record_id": event_id,
                    "confirmed_ticket_count": quote_record.get("ticket_count"),
                    "target_amount_cents": quote_record.get("total_quote_cents"),
                    "expected_inputs": [],
                }
            else:
                target_state = "COLLECTING"
                transition_code = "quote_input_incomplete"
                updates = {"quote_status": "collecting"}
                if changed_failed_quote:
                    updates.update({
                        "confirmation_status": "invalidated",
                        "active_quote_record_id": None,
                        "confirmed_quote_record_id": None,
                        "confirmation_version": None,
                        "confirmation_source": None,
                        "confirmation_event_id": None,
                        "confirmed_ticket_count": None,
                        "target_amount_cents": None,
                    })
        elif reason == "quote_confirmation_clarification_ready":
            target_state = "QUOTED"
            transition_code = "explicit_quote_confirmation_required"
            updates = {"quote_status": "ready", "confirmation_status": "pending"}
        elif (
            reason == "order_submission_guidance_ready"
            and current.quote_status == "ready"
            and current.active_quote_record_id
        ):
            target_state = "CONFIRMED"
            transition_code = "quote_confirmation_recorded"
            updates = {"quote_status": "ready", "confirmation_status": "confirmed"}
            confirmed_record = active_quote_record or (
                quote_record if isinstance(quote_record, Mapping) else None
            )
            if (
                isinstance(confirmed_record, Mapping)
                and confirmed_record.get("delivery_state") == "delivered"
                and _pick(confirmed_record, "confirmation_version")
            ):
                updates.update({
                    "confirmed_quote_record_id": _pick(
                        confirmed_record, "record_id", "quote_id",
                    ) or current.active_quote_record_id,
                    "confirmation_version": _pick(confirmed_record, "confirmation_version"),
                    "confirmation_source": _pick(confirmed_record, "confirmation_source") or "buyer_message",
                    "confirmation_event_id": event_id,
                    "confirmed_ticket_count": (
                        confirmed_record.get("confirmed_ticket_count")
                        or confirmed_record.get("ticket_count")
                    ),
                    "target_amount_cents": (
                        confirmed_record.get("total_quote_cents")
                        or current.target_amount_cents
                    ),
                })
        elif reason == "order_submission_guidance_ready":
            target_state = current.flow_state if current.flow_state != "NEW" else "COLLECTING"
            transition_code = "confirmation_without_quote_ignored"
            updates = {}
            actions = []
            decision = {**decision, "actions": [], "reason": "confirmation_without_quote_ignored"}
        elif reason == "manual_review_required":
            target_state = "MANUAL_HOLD"
            transition_code = "human_seller_takeover"
            handoff_reason = reason
        elif reason in {"authoritative_paid_status_reply_ready", "authoritative_payment_confirmation_ready"}:
            target_state = "MANUAL_HOLD"
            transition_code = "paid_amount_unverified"
            handoff_reason = transition_code
            updates = {
                "order_status": "paid", "payment_status": "verification_required",
                "fulfillment_status": "none", "order_id": order_id,
            }
            actions = []
            decision = {**decision, "actions": [], "reason": transition_code}
        elif reason == "authoritative_shipped_status_reply_ready":
            target_state = "TICKET_SENT"
            transition_code = "official_shipment_verified"
            updates = {"order_status": "shipped", "payment_status": "verified_paid", "fulfillment_status": "shipped"}
        elif reason == "authoritative_quote_expired_reply_ready":
            target_state = "QUOTE_EXPIRED"
            transition_code = "quote_expired"
            updates = {"quote_status": "expired", "confirmation_status": "invalidated"}
        elif reason in {
            "fresh_buyer_image_unavailable", "authoritative_quote_unavailable",
            "exact_order_total_unavailable", "confirmed_quote_unavailable",
        }:
            target_state = "ORDER_UNVERIFIED"
            transition_code = "order_unverified"
            updates = {"order_status": "unverified"}
        elif reason in {
            "authoritative_order_amount_already_matches_quote",
            "bound_order_amount_already_matches_quote",
            "fixed_switch_order_amount_already_matches",
        }:
            target_state = "WAITING_PAYMENT"
            transition_code = "order_amount_already_verified"
            order = body.get("order") if isinstance(body.get("order"), Mapping) else {}
            updates = {
                "quote_status": "ready", "confirmation_status": "confirmed",
                "order_status": "pending_payment", "price_change_status": "succeeded",
                "order_id": _pick(order, "orderId", "order_id"),
            }
            # The quote finder may safely fall back to an older confirmed
            # record when a newer duplicate is still being delivery-reconciled.
            # Persist the actual record used for this order, otherwise the
            # payment gate loses the confirmation lineage on the next event.
            quote_snapshot = decision.get("quote_snapshot") if isinstance(decision, Mapping) else None
            if isinstance(quote_snapshot, Mapping):
                record_id = _pick(quote_snapshot, "quote_record_id", "record_id")
                if record_id:
                    updates.update({
                        "active_quote_record_id": record_id,
                        "confirmed_quote_record_id": record_id,
                        "confirmation_version": _pick(quote_snapshot, "confirmation_version"),
                        "confirmation_source": _pick(quote_snapshot, "confirmation_source") or "buyer_message",
                        "confirmation_event_id": _pick(quote_snapshot, "confirmation_event_id"),
                        "confirmed_ticket_count": quote_snapshot.get("confirmed_ticket_count"),
                        "target_amount_cents": quote_snapshot.get("target_amount_cents"),
                    })
                    if quote_snapshot.get("fixed_switch") is True:
                        updates.update({
                            "fixed_switch_replacement_order_id": _pick(quote_snapshot, "order_id"),
                            "fixed_switch_status": "confirmed",
                            "fixed_switch_quote_confirmation_status": "confirmed",
                        })

        try:
            updated = self._store.transition(
                **identity, expected_revision=current.revision,
                event_id=f"{event_id}:decision", transition_code=transition_code,
                flow_state=target_state, updates=updates,
                allow_compatible_bootstrap=True,
            )
        except StateRevisionConflict:
            latest = self._store.get(**identity)
            if latest is None:
                raise
            stale_rule = RuleDecision(
                state_before=current.flow_state, state_after=latest.flow_state,
                transition_code="stale_event_ignored", state_revision=latest.revision,
                actions=[], handoff_reason="state_revision_conflict",
            )
            stale_decision = dict(decision)
            stale_decision.update({"actions": [], "reason": "state_revision_conflict"})
            return {**result, "decision": stale_decision, "rule_decision": stale_rule.model_dump()}
        fixed_reply = None if transition_code == "automation_hold_active" else _fixed_transaction_reply(
            state=updated.flow_state, transition_code=transition_code, event_id=event_id,
            current=updated, templates=self._templates(),
        )
        normalized_actions = [dict(action) for action in actions if isinstance(action, Mapping)]
        if fixed_reply is not None:
            fixed_text = str(fixed_reply.get("text") or "")
            normalized_actions = [fixed_reply, *[
                action for action in normalized_actions
                if not (
                    action.get("type") == "send_message"
                    and str(action.get("text") or "") == fixed_text
                )
                and (
                    action.get("type") != "send_message"
                    or action.get("preserve_on_new_buyer_message") is True
                )
            ]]
            decision = {**decision, "actions": normalized_actions}
        rule = RuleDecision(
            state_before=current.flow_state, state_after=updated.flow_state,
            transition_code=transition_code, state_revision=updated.revision,
            actions=normalized_actions, handoff_reason=handoff_reason,
        )
        return {**result, "decision": dict(decision), "rule_decision": rule.model_dump()}

    def record_action_result(
        self, *, tenant_id: str, body: Mapping[str, Any],
    ) -> RuleDecision | None:
        action_id = _pick(body, "action_id")
        event_id = _pick(body, "event_id")
        result = body.get("result") if isinstance(body.get("result"), Mapping) else None
        command_type = _pick(body, "command_type")
        if result is None or not action_id or not event_id:
            return None
        order_id = _pick(result, "order_id") or _pick(body, "order_id")
        if (
            command_type == "send_price_change_confirmation"
            and _pick(result, "reason") == "human_message_arrived_before_send"
            and order_id
        ):
            current = self._store.find_by_order(tenant_id=tenant_id, order_id=order_id)
            if current is None or current.flow_state in {"COMPLETED", "CANCELLED", "REFUNDED"}:
                return None
            result_event_id = "result:" + hashlib.sha256(f"{event_id}\\0{action_id}".encode()).hexdigest()[:40]
            updated = self._store.transition(
                tenant_id=current.tenant_id, shop_id=current.shop_id,
                buyer_id=current.buyer_id, chat_id=current.chat_id,
                expected_revision=current.revision, event_id=result_event_id,
                transition_code="explicit_human_takeover", flow_state="MANUAL_HOLD",
                updates={"automation_control": "human_hold"},
            )
            return RuleDecision(
                state_before=current.flow_state, state_after=updated.flow_state,
                transition_code="explicit_human_takeover", state_revision=updated.revision,
                actions=[], handoff_reason="explicit_human_takeover",
            )
        if command_type == "cancel_failed_liangpiao_source_order":
            if not order_id:
                return None
            current = self._store.find_by_order(tenant_id=tenant_id, order_id=order_id)
            if current is None:
                return None
            if (
                current.fixed_switch_source_platform_order_id != order_id
                or current.fixed_switch_source_order_status not in {"refund_pending", "closed"}
            ):
                return None
            source_out_order_no = _pick(result, "source_out_order_no")
            if (
                source_out_order_no
                and current.fixed_switch_source_order_no
                and source_out_order_no != current.fixed_switch_source_order_no
            ):
                return None
            status = _pick(result, "status") or "unknown"
            closed = status == "succeeded" and result.get("order_closed") is True
            transition_code = (
                "fixed_switch_source_order_closed"
                if closed else "fixed_switch_source_order_refund_pending"
            )
            result_event_id = "result:" + hashlib.sha256(
                f"{event_id}\0{action_id}".encode()
            ).hexdigest()[:40]
            updates: dict[str, object] = {
                "fixed_switch_source_order_status": "closed" if closed else "refund_pending",
                "order_status": "closed" if closed else "refund_pending",
                "payment_status": "refunded" if closed else "refund_pending",
            }
            updated = self._store.transition(
                tenant_id=current.tenant_id, shop_id=current.shop_id,
                buyer_id=current.buyer_id, chat_id=current.chat_id,
                expected_revision=current.revision, event_id=result_event_id,
                transition_code=transition_code, flow_state="MANUAL_HOLD", updates=updates,
            )
            actions: list[dict[str, Any]] = []
            if closed:
                actions.append({
                    "id": f"{event_id}:offer-fixed-after-source-closed",
                    "type": "send_message",
                    "order_id": order_id,
                    "text": "原订单已确认关闭，款项将按闲鱼平台流程原路退回。是否需要按同场次的一口价继续出票？",
                    "dedupe_key": f"{current.state_id}:offer-fixed-after-source-closed",
                    "preserve_on_new_buyer_message": True,
                    "rule_governed": True,
                    "safety_notice": True,
                })
            return RuleDecision(
                state_before=current.flow_state, state_after=updated.flow_state,
                transition_code=transition_code, state_revision=updated.revision,
                actions=actions, handoff_reason=None,
            )
        if command_type == "create_liangpiao_order":
            if not order_id:
                return None
            current = self._store.find_by_order(tenant_id=tenant_id, order_id=order_id)
            if current is None:
                return None
            result_event_id = "result:" + hashlib.sha256(f"{event_id}\\0{action_id}".encode()).hexdigest()[:40]
            status = _pick(result, "status") or "unknown"
            success = status == "succeeded" and _pick(result, "provider_order_no", "providerOrderNo", "order_no", "orderNo")
            target_state = "FULFILLMENT_IN_PROGRESS" if success else "MANUAL_HOLD"
            transition_code = "liangpiao_order_created" if success else f"liangpiao_order_create_{status}"
            updates = {
                "fulfillment_status": "claimed" if success else "none",
                "provider_status": _pick(result, "provider_status", "providerStatus") or ("created" if success else status),
                "provider_order_no": _pick(result, "provider_order_no", "providerOrderNo", "order_no", "orderNo"),
                "out_order_no": _pick(result, "out_order_no", "outOrderNo"),
            }
            updated = self._store.transition(
                tenant_id=current.tenant_id, shop_id=current.shop_id,
                buyer_id=current.buyer_id, chat_id=current.chat_id,
                expected_revision=current.revision, event_id=result_event_id,
                transition_code=transition_code, flow_state=target_state, updates=updates,
            )
            return RuleDecision(
                state_before=current.flow_state, state_after=updated.flow_state,
                transition_code=transition_code, state_revision=updated.revision,
                actions=[], handoff_reason=None if success else f"liangpiao_order_create_{status}",
            )
        if not action_id.endswith(":change-order-price"):
            return None
        if not order_id:
            return None
        current = self._store.find_by_order(tenant_id=tenant_id, order_id=order_id)
        if current is None:
            return None
        status = _pick(result, "status") or "unknown"
        target = result.get("target_amount_cents")
        verified = result.get("verified_amount_cents")
        target_state = current.flow_state
        transition_code = f"price_change_{status}"
        handoff_reason = None
        updates: dict[str, object] = {"price_change_status": status if status in {
            "succeeded", "unknown", "failed", "skipped", "rejected",
        } else "unknown"}
        if status == "skipped" and _pick(result, "reason_code") == "order_already_paid":
            target_state = "MANUAL_HOLD"
            transition_code = "payment_before_amount_verification"
            handoff_reason = "payment_before_amount_verification"
            updates.update({
                "price_change_status": "skipped", "order_status": "paid",
                "payment_status": "mismatch" if isinstance(target, int) and verified != target else "verification_required",
                "fulfillment_status": "none",
            })
        elif status == "succeeded" and isinstance(target, int) and target > 0 and verified == target:
            if current.order_status == "paid" or current.payment_status in {"verification_required", "mismatch", "verified_paid"}:
                target_state = "MANUAL_HOLD"
                transition_code = "price_change_verified_after_payment_hold"
                handoff_reason = "payment_already_observed"
                updates.update({"price_change_status": "succeeded"})
            else:
                target_state = "WAITING_PAYMENT"
                transition_code = "price_change_verified"
                updates.update({"price_change_status": "succeeded", "order_status": "pending_payment"})
        elif status in {"unknown", "failed"}:
            target_state = "MANUAL_HOLD"
            handoff_reason = f"price_change_{status}"
        result_event_id = "result:" + hashlib.sha256(f"{event_id}\0{action_id}".encode()).hexdigest()[:40]
        updated = self._store.transition(
            tenant_id=current.tenant_id, shop_id=current.shop_id,
            buyer_id=current.buyer_id, chat_id=current.chat_id,
            expected_revision=current.revision, event_id=result_event_id,
            transition_code=transition_code, flow_state=target_state, updates=updates,
        )
        return RuleDecision(
            state_before=current.flow_state, state_after=updated.flow_state,
            transition_code=transition_code, state_revision=updated.revision,
            actions=[], handoff_reason=handoff_reason,
        )
